package com.digitaq.curriculum;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Curriculum implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CURRICULUM_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "CURRICULUM_ID_GENERATOR", sequenceName = "CURRICULUM_ID_SEQ")
    private java.lang.Long id;

    public Curriculum() {
    }
    
    public Curriculum(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}